# fly.toml app configuration file generated for menukaze-worker on 2026-05-16T18:19:59+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'menukaze-worker'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'

[processes]
  worker = 'pnpm --filter @menukaze/worker start'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
